### ISSUE TITLE
upgrade to web3j 3.3.x 

### ISSUE THREAD

**Issue by shayangz** [mslinn/web3j-scala#13]
Are there any plan to upgrade to the latest web3j library?

Also, last release was back in Nov. Any idea when the next release will be cut?

**Comment by mslinn** [comment]
Should be easy to do. Would you like to submit a PR?

**Comment by shayangz** [comment]
Thanks for taking care of this. Was on my list for this week.

**Comment by shayangz** [comment]
@mslinn it looks like the v0.2.1 binaries weren't published properly. The jar is just 283 bytes and doesn't contain anything but MANIFEST.MF.

**Comment by mslinn** [comment]
Oops. Traveling. Will see what I can do, I am pressed on paying work elsewhere. Work for free is lowest priority.
