### ISSUE TITLE
bin/demo fails with "return type org.web3j.protocol.core.RemoteCall<java.lang.String> is not compatible with java.lang.String"

### ISSUE THREAD

**Issue by vigorIv2** [mslinn/web3j-scala#17]
[error] /Users/ivasilchikov/web3j-scala/abiWrapper/com/micronautics/solidity/BasicInfoGetter.java:39: getContractAddress() in com.micronautics.solidity.BasicInfoGetter cannot override getContractAddress() in org.web3j.tx.Contract
[error]   return type org.web3j.protocol.core.RemoteCall<java.lang.String> is not compatible with java.lang.String
[error]     public RemoteCall<String> getContractAddress() {
[error] (test:compileIncremental) javac returned nonzero exit code

**Comment by vigorIv2** [comment]
what would be the workaround to run ./bin/demo ?

**Comment by jopasserat** [comment]
Skip the wrapper generation, it's already in the repo for the example contract.
