### ISSUE TITLE
Verify by comparing version

### ISSUE THREAD

**Issue by djKooks** [mslinn/web3j-scala#18]
Hello.
In verifying web3 client, it seems it check only whether client version is exists or not.
```
def verifyConnection(web3j: Web3j): Boolean = try {
      web3j.web3ClientVersion.send.getWeb3ClientVersion
      true
    }
...
```
Would it be better to check in detail, like comparing current service name('geth or parity, or service in infura')? 
I'm still learner in web3, so if you think it is okay to ignore, please let me know.

Thanks.

**Comment by mslinn** [comment]
This is not an issue, this is a request for free tech support about the underlying Java library. You might read the upstream docs and check out their support options: https://github.com/web3j/web3j
