### ISSUE TITLE
web3j 4.0.0

### ISSUE THREAD

**Issue by alonbg** [mslinn/web3j-scala#25]
upgrade to web3j 4.0.0

**Comment by mslinn** [comment]
web3j 4.0.0 is only at the first alpha release. I don't have time to track early releases. If someone would like to pitch in and handle them they would be welcome ... so long as they have enough Scala background to accomplish that without calling me for help all the time.

**Comment by alonbg** [comment]
right.
Also, it seems, web3j 4.0.0 uses rxJava2 while I make use of [rxScala](https://github.com/ReactiveX/RxScala) which supports only rxJava 1.x

**Comment by mslinn** [comment]
I created branch 4.1.1, which probably will be good to go once [this issue](https://github.com/web3j/web3j/issues/862) is resolved.

**Comment by mslinn** [comment]
Looks like the replacement for `catchUpToLatestAndSubscribeToNewBlocksObservable` is `replayPastAndFutureBlocksFlowable`. Getting ready to publish a new version, stay tuned...

**Comment by mslinn** [comment]
v4.1.1 has been published
