### ISSUE TITLE
Unresolved dependencies

### ISSUE THREAD

**Issue by wnz99** [mslinn/web3j-scala#42]
Hi,

I tried to follow the setup instructions to use as a library but got the following error:

```
INFO  [warn] 
INFO  [warn] 	Note: Unresolved dependencies path:
INFO  [error] sbt.librarymanagement.ResolveException: Error downloading org.ethereum:solcJ-all:0.4.24
INFO  [error]   Not found
INFO  [error]   Not found
INFO  [error]   not found: /home/whitenoise/.ivy2/local/org.ethereum/solcJ-all/0.4.24/ivys/ivy.xml
INFO  [error]   not found: https://repo1.maven.org/maven2/org/ethereum/solcJ-all/0.4.24/solcJ-all-0.4.24.pom
INFO  [error]   not found: https://dl.bintray.com/micronautics/scala/org/ethereum/solcJ-all/0.4.24/solcJ-all-0.4.24.pom
```

Removing:

`resolvers += "micronautics/scala on bintray" at "https://dl.bintray.com/micronautics/scala"`

and adding:

`resolvers += "ethereum" at "https://dl.bintray.com/ethereum/maven/"`

seems to solve the issue.

Please not that I'm totally new to Scala and sbt so not really sure about what's going on.

**Comment by mslinn** [comment]
Seems like both resolvers should be specified. Probably the reason you did not require the first resolver is because you only wrote Scala code that directly accessed the Java library (found via the second resolver). I'll update the README to say:

```scala
resolvers ++= Seq(
  "micronautics/scala on bintray" at "https://dl.bintray.com/micronautics/scala",
  "ethereum" at "https://dl.bintray.com/ethereum/maven/"
)
```
