### ISSUE TITLE
Suggestion: apply for a Gitcoin grant in the next wave (or maybe current wave if possible, but it ends in 4 days)

### ISSUE THREAD

**Issue by ryanberckmans** [mslinn/web3j-scala#44]
https://gitcoin.co/grants/

**Comment by mslinn** [comment]
Ryan,
Thanks for the suggestion. I created an contributor account. Where do I indicate that this project exists and could be funded?
Mike

**Comment by ryanberckmans** [comment]
Mike, actually it looks like registration for new grant recipients may be
closed because the current funding round is in progress. Gitcoin does this
pretty often so you can probably get in the next round. It's good publicity
for the project, too.

**Comment by mslinn** [comment]
This is messed up
