### ISSUE TITLE
Dependency missing

### ISSUE THREAD

**Issue by Reeebuuk** [mslinn/web3j-scala#6]
Hi guys,

when I pull the project solidity lib is missing.

Error:(24, 27) object solidity is not a member of package com.micronautics
  import com.micronautics.solidity._

**Comment by mslinn** [comment]
The documentation should explain several related concepts, but it does not (yet). The docs tell you how to run the demos using the scripts but probably don't provide enough information for others to use this project. Let's fix that.

The Solidity smart contract is in the [abiWrapper/com/micronautics/solidity](https://github.com/mslinn/web3j-scala/tree/master/abiWrapper/com/micronautics/solidity) directory. 

This line in `build.sbt` adds that directory to the collection of source code directories:

    unmanagedSourceDirectories in Compile += baseDirectory.value / "../abiWrapper"

The Java file in the `abiWrapper` directory is created when SBT runs by compiling the Solidity smart contract provided with this project. 

Presumably you tried to use this project as a library (is that true?) If you tell me how you attempted to use this project, I'll write some matching documentation.

**Comment by Reeebuuk** [comment]
Thanks for the fast response :)

Yes I wanted to use it as a library but at the same time wanted to take a look at the source code to see what's happening under the hood. So the first thing I wanted to do is compile and run the tests.

It's compiling now per your instructions :) forgot to run `sbt compile`, have just run compilation in intellij.

When I wanted to import web3j-scala as lib in my project I had to add:

`resolvers += "ethereum" at "https://dl.bintray.com/ethereum/maven/"`

otherwise it couldn't find one dependent lib. I see that you have it in your sbt so don't know why it didn't catch it.

**Comment by mslinn** [comment]
PRs for better docs are gladly accepted :)
